[workspace]
members = ["day01_1", "day01_2", "day02_1", "day02_2", "day03_1", "day03_2", "day04_1", "day04_2", "day05_1", "day05_2"]
resolver = "2"

[workspace.package]
authors = ["Augustyn Majtyka"]
description = "Advent of Code 2023"
version = "0.1.0"